### PR TITLE
Fix: Declare otherwise dynamically declared property

### LINKED ISSUE #258: PHP 8.2 deprecations
#### Steps required to reproduce the problem

1. Be on PHP 8.2
2. Run twigcs

#### Expected Result

- No deprecations

#### Actual Result

- `Deprecated: Creation of dynamic property FriendsOfTwig\Twigcs\Rule\UnusedMacro::$loader is deprecated`
- `PHP Deprecated:  Creation of dynamic property FriendsOfTwig\Twigcs\Rule\UnusedVariable::$loader`

### PR DESCRIPTION
**Pull request by localheinz**
This pull request

- [x] disallows deprecations
- [x] declares otherwise dynamically declared properties
- [x] runs `make static-code-analysis-baseline`

Fixes #258.

### CODE REVIEW

File: src/Rule/UnusedMacro.php [hunk 1]
```diff
@@ -9,6 +9,8 @@
 
 class UnusedMacro extends AbstractRule implements RuleInterface
 {
+    public TemplateResolverInterface $loader;
```
Comment (localheinz) [inline src/Rule/UnusedMacro.php:12]: Declaring this property as `public` as otherwise it would be a backwards-incompatible change.
